@startuml
left to right direction
actor Customer #00684a;line:green;line.bold;text:green
actor "Payment Gateway" #00684a;line:green;line.bold;text:green
rectangle "Mutual Fund" #00000000;line:green;text:green{
    usecase Login #00684a;line:green;line.bold;text:white
    usecase "Browse Catalog Mutual Fund" #00684a;line:green;line.bold;text:white
    usecase "Checkout" #00684a;line:green;line.bold;text:white
    usecase "Update Transaction Status" #00684a;line:green;line.bold;text:white
    usecase "Check Transaction History" #00684a;line:green;line.bold;text:white
}

Customer --> Login
Customer --> "Browse Catalog Mutual Fund"
Customer --> "Checkout"
Customer --> "Check Transaction History"
"Payment Gateway" --> "Update Transaction Status"
@enduml
